// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPrivacyProfileRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NodeMetadata {
    #[prost(string, tag = "1")]
    pub implementation: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub revision: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MethodPolicy {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "MethodRiskClass", tag = "2")]
    pub risk_class: i32,
    #[prost(bool, tag = "3")]
    pub enabled: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPrivacyProfileResponse {
    #[prost(string, tag = "1")]
    pub capability_version: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub policy_version: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub service_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub network: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub node: ::core::option::Option<NodeMetadata>,
    #[prost(enumeration = "EndpointProfile", tag = "6")]
    pub endpoint_profile: i32,
    #[prost(message, repeated, tag = "7")]
    pub methods: ::prost::alloc::vec::Vec<MethodPolicy>,
    #[prost(enumeration = "LoggingMode", tag = "8")]
    pub logging_mode: i32,
    #[prost(uint32, tag = "9")]
    pub metric_window_seconds: u32,
    #[prost(bool, tag = "10")]
    pub supports_writes: bool,
    #[prost(bool, tag = "11")]
    pub persistent_client_identifiers: bool,
    #[prost(bool, tag = "12")]
    pub cookies: bool,
    #[prost(bool, tag = "13")]
    pub affinity: bool,
    #[prost(string, tag = "14")]
    pub valid_from: ::prost::alloc::string::String,
    #[prost(string, tag = "15")]
    pub valid_until: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "16")]
    pub canonical_json: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EndpointProfile {
    Unspecified = 0,
    Legacy = 1,
    Privacy = 2,
}
impl EndpointProfile {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ENDPOINT_PROFILE_UNSPECIFIED",
            Self::Legacy => "ENDPOINT_PROFILE_LEGACY",
            Self::Privacy => "ENDPOINT_PROFILE_PRIVACY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ENDPOINT_PROFILE_UNSPECIFIED" => Some(Self::Unspecified),
            "ENDPOINT_PROFILE_LEGACY" => Some(Self::Legacy),
            "ENDPOINT_PROFILE_PRIVACY" => Some(Self::Privacy),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MethodRiskClass {
    Unspecified = 0,
    CommonChainData = 1,
    TransactionSpecificLookup = 2,
    TransparentAddressLookup = 3,
    MempoolPersonalization = 4,
    TransactionSubmission = 5,
    AdministrationDebug = 6,
}
impl MethodRiskClass {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "METHOD_RISK_CLASS_UNSPECIFIED",
            Self::CommonChainData => "METHOD_RISK_CLASS_COMMON_CHAIN_DATA",
            Self::TransactionSpecificLookup => {
                "METHOD_RISK_CLASS_TRANSACTION_SPECIFIC_LOOKUP"
            }
            Self::TransparentAddressLookup => {
                "METHOD_RISK_CLASS_TRANSPARENT_ADDRESS_LOOKUP"
            }
            Self::MempoolPersonalization => "METHOD_RISK_CLASS_MEMPOOL_PERSONALIZATION",
            Self::TransactionSubmission => "METHOD_RISK_CLASS_TRANSACTION_SUBMISSION",
            Self::AdministrationDebug => "METHOD_RISK_CLASS_ADMINISTRATION_DEBUG",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "METHOD_RISK_CLASS_UNSPECIFIED" => Some(Self::Unspecified),
            "METHOD_RISK_CLASS_COMMON_CHAIN_DATA" => Some(Self::CommonChainData),
            "METHOD_RISK_CLASS_TRANSACTION_SPECIFIC_LOOKUP" => {
                Some(Self::TransactionSpecificLookup)
            }
            "METHOD_RISK_CLASS_TRANSPARENT_ADDRESS_LOOKUP" => {
                Some(Self::TransparentAddressLookup)
            }
            "METHOD_RISK_CLASS_MEMPOOL_PERSONALIZATION" => {
                Some(Self::MempoolPersonalization)
            }
            "METHOD_RISK_CLASS_TRANSACTION_SUBMISSION" => {
                Some(Self::TransactionSubmission)
            }
            "METHOD_RISK_CLASS_ADMINISTRATION_DEBUG" => Some(Self::AdministrationDebug),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LoggingMode {
    Unspecified = 0,
    MethodLevelRequest = 1,
    PrivacyAggregateOnly = 2,
}
impl LoggingMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LOGGING_MODE_UNSPECIFIED",
            Self::MethodLevelRequest => "LOGGING_MODE_METHOD_LEVEL_REQUEST",
            Self::PrivacyAggregateOnly => "LOGGING_MODE_PRIVACY_AGGREGATE_ONLY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LOGGING_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "LOGGING_MODE_METHOD_LEVEL_REQUEST" => Some(Self::MethodLevelRequest),
            "LOGGING_MODE_PRIVACY_AGGREGATE_ONLY" => Some(Self::PrivacyAggregateOnly),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod privacy_profile_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct PrivacyProfileServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PrivacyProfileServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PrivacyProfileServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PrivacyProfileServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            PrivacyProfileServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_privacy_profile(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPrivacyProfileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPrivacyProfileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zaino.privacy.v1.PrivacyProfileService/GetPrivacyProfile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zaino.privacy.v1.PrivacyProfileService",
                        "GetPrivacyProfile",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod privacy_profile_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with PrivacyProfileServiceServer.
    #[async_trait]
    pub trait PrivacyProfileService: std::marker::Send + std::marker::Sync + 'static {
        async fn get_privacy_profile(
            &self,
            request: tonic::Request<super::GetPrivacyProfileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPrivacyProfileResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct PrivacyProfileServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> PrivacyProfileServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for PrivacyProfileServiceServer<T>
    where
        T: PrivacyProfileService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/zaino.privacy.v1.PrivacyProfileService/GetPrivacyProfile" => {
                    #[allow(non_camel_case_types)]
                    struct GetPrivacyProfileSvc<T: PrivacyProfileService>(pub Arc<T>);
                    impl<
                        T: PrivacyProfileService,
                    > tonic::server::UnaryService<super::GetPrivacyProfileRequest>
                    for GetPrivacyProfileSvc<T> {
                        type Response = super::GetPrivacyProfileResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetPrivacyProfileRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PrivacyProfileService>::get_privacy_profile(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetPrivacyProfileSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for PrivacyProfileServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "zaino.privacy.v1.PrivacyProfileService";
    impl<T> tonic::server::NamedService for PrivacyProfileServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
